# Generated by Django 3.0.7 on 2020-11-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcreate',
            name='taskTitle',
            field=models.CharField(default='Task-', max_length=50),
        ),
    ]
