# Generated by Django 3.0.7 on 2020-11-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201126_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskContent',
        ),
        migrations.DeleteModel(
            name='TaskCreate',
        ),
    ]
