# Generated by Django 3.0.7 on 2020-11-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_auto_20201126_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Create Task',
            },
        ),
    ]
