# Generated by Django 3.0.7 on 2020-11-27 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tasklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='taskTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 27, 18, 39, 28, 611838, tzinfo=utc)),
        ),
    ]
