# Generated by Django 3.0.7 on 2020-11-27 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201128_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='taskTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 27, 18, 43, 3, 319920, tzinfo=utc)),
        ),
    ]
