# Generated by Django 3.0.7 on 2020-11-28 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20201128_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='taskTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 11, 28, 10, 40, 22, 355236, tzinfo=utc)),
        ),
    ]
