# Generated by Django 3.0.7 on 2020-11-29 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20201130_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='taskTime',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 11, 29, 18, 48, 19, 839591, tzinfo=utc), null=True),
        ),
    ]
